const mongoose = require('mongoose');

const dataSchema = new mongoose.Schema({
  v1: Number,
  v2: Number,
  v3: Number,
  v4: Number,
  v5: Number,
  v6: Number,
  v7: Number,
  v8: Number,
  v9: Number,
  v10: Number,
  v11: Number,
  v12: Number,
  v13: Number,
  v14: Number,
  v15: Number,
  v16: Number,
  v17: Number,
  v18: Number,
  v19: Number,
  v20: Number,
  v21: Number,
  v22: Number,
  v23: Number,
  v24: Number,
  v25: Number,
  v26: Number,
  v27: Number,
  v28: Number,
  v29: Number,
  v30: Number,
  v31: Number,
  v32: Number,
  v33: Number,
  v34: Number,
  v35: Number,
  v36: Number,
  v37: Number,
  v38: Number,
  v39: Number,
  v40: Number,
  v41: Number,
  v42: Number,
  v43: Number,
  v44: Number,
  v45: Number,
  v46: Number,
  v47: Number,
  v48: Number,
  v49: Number,
  v50: Number,
  v51: Number,
  v52: Number,
  v53: Number,
  v54: String,
  v55: String,
  v56: Number,
  v57: Number,
  v58: Number,
  v59: Number,
  v60: Number,
  date: {
    type: Date,
    default: () => new Date().toISOString().slice(0, 10)
  },
  user: String,
  timestamp: {
    type: Date,
    default: Date.now,
    get: function(v) {
      return new Date(v).toLocaleString('en-US', { timeZone: 'Asia/Kolkata' });
    },
  },
});

// const dataSchema = new mongoose.Schema({
//   user: String,
//   userID: Number,
//   date: String,
//   timestamp: {
//     type: Date,
//     default: Date.now,
//     get: function(v) {
//       return new Date(v).toLocaleString('en-US', { timeZone: 'Asia/Kolkata' });
//     },
//   },
//   motion:{
//     speed: Number,
//     rpm: Number,
//     distance: Number,
//     trip: Number,
//     slope: Number,
//     mode: Number,
//   },
//   temperature:{
//     controllerTemperature: Number,
//     motorTemperature: Number,
//     ambientTemperature: Number,
//     otherTemperature: Number,
//     controllerFault: Number,
//   },
//   battery1:{
//     voltage: Number,
//     current: Number,
//     soc: Number,
//     power: Number,
//     watthr: Number,
//     range: Number,
//     charging: Number,
//     batteryFault: Number,
//     lowCell: Number,
//     highCell: Number,
//     avgCell: Number,
//     cell:{
//       v1: Number,
//       v2: Number,
//       v3: Number,
//       v4: Number,
//       v5: Number,
//       v6: Number,
//       v7: Number,
//       v8: Number,
//       v9: Number,
//       v10: Number,
//       v11: Number,
//       v12: Number,
//       v13: Number,
//       v14: Number,
//       v15: Number,
//       v16: Number,
//       v17: Number,
//       v18: Number,
//       v19: Number,
//       v20: Number,
//       v21: Number,
//       v22: Number,
//       v23: Number,
//       v24: Number,
//     }
//   },
//   battery2:{
//     voltage: Number,
//     current: Number,
//     soc: Number,
//     power: Number,
//     watthr: Number,
//     range: Number,
//     charging: Number,
//     batteryFault: Number,
//     lowCell: Number,
//     highCell: Number,
//     avgCell: Number,
//     cell:{
//       v1: Number,
//       v2: Number,
//       v3: Number,
//       v4: Number,
//       v5: Number,
//       v6: Number,
//       v7: Number,
//       v8: Number,
//       v9: Number,
//       v10: Number,
//       v11: Number,
//       v12: Number,
//       v13: Number,
//       v14: Number,
//       v15: Number,
//       v16: Number,
//       v17: Number,
//       v18: Number,
//       v19: Number,
//       v20: Number,
//       v21: Number,
//       v22: Number,
//       v23: Number,
//       v24: Number,
//     }
//   },
//   battery3:{
//     voltage: Number,
//     current: Number,
//     soc: Number,
//     power: Number,
//     watthr: Number,
//     range: Number,
//     charging: Number,
//     batteryFault: Number,
//     lowCell: Number,
//     highCell: Number,
//     avgCell: Number,
//     cell:{
//       v1: Number,
//       v2: Number,
//       v3: Number,
//       v4: Number,
//       v5: Number,
//       v6: Number,
//       v7: Number,
//       v8: Number,
//       v9: Number,
//       v10: Number,
//       v11: Number,
//       v12: Number,
//       v13: Number,
//       v14: Number,
//       v15: Number,
//       v16: Number,
//       v17: Number,
//       v18: Number,
//       v19: Number,
//       v20: Number,
//       v21: Number,
//       v22: Number,
//       v23: Number,
//       v24: Number,
//     }
//   },
// });

const Data = mongoose.model('Data', dataSchema);
module.exports = Data;
